#!/usr/bin/env python3
"""Embeds the main toolbar SVGs into include/main_toolbar_icons.h.

The artwork in resources/images/ToolbarIcons colors its shapes through CSS
classes in a <style> block, which nanosvg (wxBitmapBundle::FromSVG) ignores,
so the shapes would render black. Each class is folded into the element's
inline style attribute, which nanosvg does read.

Run from the repository root:  python build_scripts/generate_toolbar_svg_header.py
"""

import os
import re

SOURCE_DIR = os.path.join("resources", "images", "ToolbarIcons")
OUTPUT = os.path.join("include", "main_toolbar_icons.h")

# Icon file -> C identifier stem.
ICONS = {
    "New Sequence.svg": "new_sequence",
    "Open Sequence.svg": "open_sequence",
    "Save.svg": "save",
    "Save As.svg": "save_as",
    "Show Folder.svg": "show_folder",
    "Render.svg": "render",
    "Paste by Time.svg": "paste_by_time",
    "Paste by Cell.svg": "paste_by_cell",
    "Play.svg": "play",
    "Pause.svg": "pause",
    "Stop.svg": "stop",
    "First Frame.svg": "first_frame",
    "Last Frame.svg": "last_frame",
    "Replay Selection.svg": "replay",
    "Settings.svg": "settings",
    "Zoom In.svg": "zoom_in",
    "Zoom Out.svg": "zoom_out",
    "Model Preview.svg": "model_preview",
    "House Preview.svg": "house_preview",
    "Display Elements.svg": "display_elements",
    "Effects.svg": "effects",
    "Effect Colors.svg": "effect_colors",
    "Effect Settings.svg": "effect_settings",
    "Layer Blending.svg": "layer_blending",
    "Layer Settings.svg": "layer_settings",
    "AC On.svg": "ac_on",
    "AC Off.svg": "ac_off",
    "AC Select.svg": "ac_select",
    "AC Shimmer.svg": "ac_shimmer",
    "AC Twinkle.svg": "ac_twinkle",
    "AC Intensity.svg": "ac_intensity",
    "AC Ramp Up.svg": "ac_ramp_up",
    "AC Ramp Down.svg": "ac_ramp_down",
    "AC Ramp Up Ramp Down.svg": "ac_ramp_up_down",
    "AC Fill.svg": "ac_fill",
    "AC Cascade.svg": "ac_cascade",
    "AC Foreground.svg": "ac_foreground",
    "AC Background.svg": "ac_background",
}


def inline_classes(svg):
    rules = {}
    for style in re.findall(r"<style[^>]*>(.*?)</style>", svg, re.S):
        for selectors, body in re.findall(r"([^{}]+)\{([^}]*)\}", style):
            for selector in selectors.split(","):
                selector = selector.strip()
                if selector.startswith("."):
                    rules.setdefault(selector[1:], []).append(body.strip().rstrip(";"))
    svg = re.sub(r"<style[^>]*>.*?</style>", "", svg, flags=re.S)
    svg = re.sub(r"<defs>\s*</defs>", "", svg)

    def replace(match):
        tag = match.group(0)
        classes = match.group(2).split()
        declarations = [d for c in classes for d in rules.get(c, [])]
        tag = tag.replace(match.group(1), "", 1)
        if not declarations:
            return tag
        style = ";".join(declarations)
        existing = re.search(r'\sstyle="([^"]*)"', tag)
        if existing:
            return tag.replace(existing.group(0), ' style="%s;%s"' % (style, existing.group(1)), 1)
        return tag[:-2] + ' style="%s"/>' % style if tag.endswith("/>") else tag[:-1] + ' style="%s">' % style

    return re.sub(r'<[a-zA-Z][^>]*?(\sclass="([^"]*)")[^>]*>', replace, svg)


def main():
    lines = [
        "#pragma once",
        "",
        "// Generated by build_scripts/generate_toolbar_svg_header.py from",
        "// resources/images/ToolbarIcons. Do not edit by hand.",
        "",
        "#include <cstddef>",
        "",
    ]
    for filename, stem in ICONS.items():
        with open(os.path.join(SOURCE_DIR, filename), encoding="utf-8") as f:
            data = inline_classes(f.read()).encode("utf-8")
        lines.append("static const unsigned char main_toolbar_%s_svg[] = {" % stem)
        for i in range(0, len(data), 16):
            lines.append("    " + ", ".join("0x%02x" % b for b in data[i:i + 16]) + ",")
        lines.append("};")
        lines.append("static const size_t main_toolbar_%s_svg_len = %d;" % (stem, len(data)))
        lines.append("")
    with open(OUTPUT, "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(lines))


if __name__ == "__main__":
    main()
